import { StyleSheet } from 'react-native';
import { COLORS, fontStyle, H_PAD } from './constants';
 
export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: COLORS.surface },
  scroll: { flex: 1 },
  scrollContent: { paddingBottom: 12 },
 
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: H_PAD,
    paddingVertical: 16,
  },
  topBarBtn: { width: 24, height: 24, justifyContent: 'center' },logo: { width: 250, height: 150},
  hamburgerLine: { width: 18, height: 2, backgroundColor: COLORS.bodyDark, borderRadius: 1 },
  
  searchWrap: { paddingHorizontal: H_PAD, marginBottom: 32 },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.inputBg,
    borderRadius: 9999,
    paddingLeft: 16,
    paddingRight: 48,
    height: 56,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: COLORS.bodyDark,
    ...fontStyle('regular'),
    padding: 0,
  },
  searchIconWrap: {
    position: 'absolute',
    right: 18,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
  },
  clearSearch: { position: 'absolute', left: 50, padding: 8 },
 
  section: { marginBottom: 32, paddingHorizontal: H_PAD },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 19,
    lineHeight: 26,
    color: COLORS.titleDark,
    ...fontStyle('bold'),
    textAlign: 'right',
  },
  sectionAction: { fontSize: 14, lineHeight: 20, color: COLORS.primary, ...fontStyle('bold') },
 
  greenPillBtn: {
    backgroundColor: COLORS.primary,
    borderRadius: 9999,
    paddingHorizontal: 20,
    paddingVertical: 8,
  },
  greenPillBtnText: { fontSize: 14, color: COLORS.white, ...fontStyle('bold') },
 
  pillRow: { flexDirection: 'row', gap: 8, paddingHorizontal: H_PAD },
  pill: { borderRadius: 9999, paddingHorizontal: 18, paddingVertical: 10 },
  pillActive: { backgroundColor: COLORS.primary },
  pillInactive: { backgroundColor: '#E4E2E1' },
  pillText: { fontSize: 15, ...fontStyle('medium') },
  pillTextActive: { color: COLORS.white },
  pillTextInactive: { color: COLORS.bodyDark },
 
  promoWrap: { paddingHorizontal: H_PAD, marginBottom: 32 },
  promoBanner: {
    height: 200,
    borderRadius: 32,
    overflow: 'hidden',
    backgroundColor: '#2C3828',
    justifyContent: 'center',
  },
  promoSpecialBadge: {
    position: 'absolute',
    top: 16,
    right: 20,
    backgroundColor: COLORS.promoBadge,
    borderRadius: 9999,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  promoSpecialText: { fontSize: 12, color: COLORS.white, ...fontStyle('bold') },
  promoTextBlock: { position: 'absolute', top: 48, right: 20, alignItems: 'flex-end' },
  promoDiscount: { fontSize: 28, color: COLORS.white, ...fontStyle('bold'), marginBottom: 6 },
  promoSub: {
    fontSize: 13,
    lineHeight: 20,
    color: 'rgba(255,255,255,0.8)',
    textAlign: 'right',
    ...fontStyle('regular'),
  },
  promoBtn: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    backgroundColor: '#F7F3EA',
    borderRadius: 9999,
    paddingHorizontal: 20,
    paddingVertical: 8,
  },
  promoBtnText: { fontSize: 13, color: COLORS.primary, ...fontStyle('bold') },
 
  hCardRow: { flexDirection: 'row', gap: 14, paddingHorizontal: H_PAD },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 },
 
  card: { backgroundColor: COLORS.surfaceCard, borderRadius: 24, overflow: 'hidden' },
  cardImgWrap: { width: '100%' },
  cardImg: { width: '100%', height: '100%' },
  cardBody: { padding: 10, gap: 2 },
  cardWeight: {
    fontSize: 11,
    color: COLORS.mutedText,
    textAlign: 'right',
    ...fontStyle('regular'),
  },
  cardName: {
    fontSize: 13,
    lineHeight: 20,
    color: COLORS.titleDark,
    ...fontStyle('bold'),
    textAlign: 'right',
    marginBottom: 6,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardPrice: { fontSize: 15, color: COLORS.primary, fontWeight: '900' },
 
  // Plain + button (qty === 0)
  addBtn: {
    width: 32,
    height: 32,
    borderRadius: 9999,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addBtnText: { fontSize: 20, color: COLORS.white, lineHeight: 24, marginTop: -1 },
 
  // Quantity stepper (qty > 0)
  stepper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    borderRadius: 9999,
    height: 32,
    paddingHorizontal: 4,
    gap: 2,
  },
  stepperBtn: {
    width: 26,
    height: 26,
    borderRadius: 9999,
    backgroundColor: 'rgba(255,255,255,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperBtnText: { fontSize: 16, color: COLORS.white, lineHeight: 20, marginTop: -1 },
  stepperQty: {
    minWidth: 20,
    textAlign: 'center',
    fontSize: 14,
    color: COLORS.white,
    ...fontStyle('bold'),
  },
 
  heartBtn: {
    position: 'absolute',
    top: 8,
    left: 8,
    width: 30,
    height: 30,
    borderRadius: 9999,
    backgroundColor: 'rgba(255,255,255,0.85)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heartIcon: { fontSize: 13, color: COLORS.primary },
 
  greenBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: COLORS.badgeLightBg,
    borderRadius: 9999,
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  greenBadgeText: { fontSize: 10, color: COLORS.badgeLightTx, ...fontStyle('bold') },
 
  bottomNav: {
    flexDirection: 'row',
    backgroundColor: COLORS.surfaceCard,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingBottom: 24,
    paddingTop: 12,
    paddingHorizontal: 16,
    gap: 6,
    shadowColor: '#3F4A3C',
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.06,
    shadowRadius: 40,
    elevation: 12,
  },
  navItem: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  navIconWrap: { alignItems: 'center', gap: 2 },
  navIcon: { fontSize: 18, color: COLORS.navInactive },
  navIconActive: { color: COLORS.primary },
  navLabel: { fontSize: 10, lineHeight: 15, color: COLORS.navInactive, ...fontStyle('medium') },
  navLabelActive: { color: COLORS.primary },
 
  navCartBadge: {
    position: 'absolute',
    top: -4,
    right: -6,
    width: 15,
    height: 15,
    borderRadius: 9999,
    backgroundColor: COLORS.cartBadge,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navCartBadgeText: { fontSize: 9, color: '#F7F3EA', ...fontStyle('regular') },
 
  navActivePill: {
    backgroundColor: COLORS.primary,
    borderRadius: 9999,
    paddingHorizontal: 14,
    paddingVertical: 7,
    alignItems: 'center',
    gap: 2,
  },
  navActivePillIcon: { fontSize: 15, color: COLORS.surfaceCard },
  navActivePillLabel: { fontSize: 10, color: COLORS.surfaceCard, ...fontStyle('medium') },
 
  // Flying dot
  flyingDot: {
    position: 'absolute',
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: COLORS.primary,
    zIndex: 9999,
  },
});